### ISSUE TITLE
Is there any way to change the font of the text on the card?

### ISSUE THREAD

**Issue by timelic** [SethPDA/MasterDuel-Modding#1]
I'm using a translation plugin because the game doesn't have a translation for my language. But the plugin creator just replaces the English text, which causes the font to be missing and is not pretty.
I would like to know if there is a way to modify the font of the text on the cards to have a better experience.

**Comment by SethPDA** [comment]
As of right now, it's still a wip.
You can try the same method shown in the guide, but instead of music, place a font, and build it in Unity, then replace the files, see if that helps.
