### ISSUE TITLE
Changing sprites

### ISSUE THREAD

**Issue by zeak6464** [SethPDA/MasterDuel-Modding#2]
Been trying to edit protectors following this music guide but having issues with unity shardedassets not showing when i build.

**Comment by SethPDA** [comment]
I'm not sure which part of the guide is causing this issue, but you need to place every asset into a scene when you build, and also, that scene has to be included in the build window so Unity builds it fine.

**Comment by SethPDA** [comment]
Shared assets show up only if you include the modified files in a unity scene and then save that too. Otherwise the built package will be empty and will contain only standard unity stuff.
