### ISSUE TITLE
Mesh Modding 

### ISSUE THREAD

**Issue by asdasdasdasd7462** [SethPDA/MasterDuel-Modding#3]
First of all, thank you for your work, now, I have been keeping tabs on the mesh modding part of your wiki but it has not been updated, i already  managed to replace the dark magician body with the dark magician girl body but it shows up very tiny and in A position, hope it gets updated soon so I can try replacing things because currently i have no idea of what am I doing, thank you in advance

**Comment by SethPDA** [comment]
Added mesh modding. Sorry it took so long.
