### ISSUE TITLE
Cannot find correct CAP file location

### ISSUE THREAD

**Issue by Awesome456** [SethPDA/MasterDuel-Modding#4]
I found that the sound effect that I wanted to replace, se_effect_invalid, was not found in the LocalData folder but instead in the masterduel_Data folder. When extracting that folder, I am unable to play the audio files found within it.

Preview AudioClip:SE_EFFECT_INVALID error
Can't find the resource file resources.resource
at AssetStudio.ResourceReader.GetReader()----------and much more

For some reason AssetStudio cannot find the resource file attached to it. this makes it so when trying to find the original file, I cannot find the CAP file that it is attached to. I've tried extracting the entire Master duel folder to see if that would somehow get the resource file but the problem still remained. How can I find this CAP file so that I can make the replacement?

**Comment by SethPDA** [comment]
I haven't even tried extracting the masterduel data folder so I cannot comment on this. My guides focus on the localdata folder. Maybe in the future I will try, but for now I will close this issue.
